[msg MSG_006_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Once we got to talking, we realized[n]we all had the same plans...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Um... Would you care for some of these[n]as well?[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Then it was definitely worth making[n]seconds![n][f 1 3 65535][w][e]

