[msg MSG_000_0_0 [Prurient Employee]]
[s][vp 8 0 0 0 65535 0]Did you hear the news?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Gossipy Employee]]
[s][vp 8 0 0 0 65535 0]I did...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Gossipy Employee]]
[s][vp 8 0 0 0 65535 0]I just got it from him face-to-face.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]They're saying he's leaving soon, right?[n]Even though he only just got here.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Prurient Employee]]
[s][vp 8 0 0 0 65535 0]That kid was tiny when he left with his mother,[n]wasn't he? How many years has it been...?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]We were so excited. He'd just come back all[n]grown-up and handsome, and now...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Gossipy Employee]]
[s][vp 8 0 0 0 65535 0]At least he still remembered he could[n]come here, though.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]After all, that's what this place is for.[n]To shelter people like us, who have a[n]past they can't forget.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Especially someone we've known for so long.[n]As if we wouldn't hide him when he needed it.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Prurient Employee]]
[s][vp 8 0 0 0 65535 0]I heard he said he has "unfinished business in Tokyo."[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Gossipy Employee]]
[s][vp 8 0 0 0 65535 0]You really do know it all, don't you?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Prurient Employee]]
[s][vp 8 0 0 0 65535 0]Tell me, though...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Prurient Employee]]
[s][vp 8 0 0 0 65535 0]That "unfinished business" of his—[n]that's what this is all about, right?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Young Man's Voice]]
[s][vp 8 0 0 0 65535 0]I wish you'd keep your nose out of my affairs.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Prurient Employee]]
[s][vp 8 0 0 0 65535 0]You tell me, then, if you're right there![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Gossipy Employee]]
[s][vp 8 0 0 0 65535 0]He did say there was someone who[n]helped him out in Tokyo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]So he's going back because he owes him.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Gossipy Employee]]
[s][vp 8 0 0 0 65535 0]Right?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Young Man's Voice]]
[s][vp 8 0 0 0 65535 0]Don't worry, I'll clear my debts here before I leave.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]For taking me in last year... on Christmas Eve,[n]was it? Without an appointment.[n]Without asking questions.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]That, and for everything you did for my mother.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Prurient Employee]]
[s][vp 8 0 0 0 65535 0]Never mind that. To go to these lengths just[n]because you owe somebody...[n]No, I guess that's you all over, isn't it.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Young Man's Voice]]
[s][vp 8 0 0 0 65535 0]If it works out, then he and his friends[n]will live out their lives...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...Well, they'll owe me their thanks forever.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Young Man's Voice]]
[s][vp 8 0 0 0 65535 0]I'm going to sweep up outside.[n][f 1 3 65535][w][e]

