[msg MSG_024_0_0 [Kasumi]]
[s][bup 0 10 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S-Senpai! Could you... Could you bring[n]some over here too!?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Kasumi]]
[s][bup 0 10 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I never imagined we'd get such a gift in[n]return... My heart is so full right now![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Kasumi]]
[s][bup 0 10 4 4 0][vp 8 0 0 0 0 0]......![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Futaba]]
[s][bup 0 8 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hey, Kasumi actually got the vapors![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Kasumi]]
[s][bup 0 10 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*gasp* S-Sorry about that...[n][f 1 3 65535][w][e]
